#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width         2
bspc config window_gap          10

bspc config normal_border_color	"404552"
bspc config focused_border_color "c4cbd4"

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp state=floating follow=on

xwallpaper --stretch "$HOME/.local/share/background" &
picom &
$HOME/.config/polybar/launch.sh &
